name: 'doc'

on:
  push:
    paths:
      - '.github/workflows/doc.yml'
      - 'doc/**'
      - 'vhdl202x-lcs-dpi/**'

jobs:


  btd:
    name: '📓 Docs'
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Build bookdown site and PDF
      run: |
        docker build -t bookdown - < vhdl202x-lcs-dpi/Rmd/Dockerfile
        docker run --rm -v $(pwd):/src -w /src/vhdl202x-lcs-dpi bookdown
        mkdir -p public
        cp -r vhdl202x-lcs-dpi/_book public/vhdl202x

    - name: '📓 BuildTheDocs (BTD)'
      uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}

    - name: '📤 Upload artifact: HTML'
      uses: actions/upload-artifact@master
      with:
        name: doc
        path: doc/_build/html
